

# POST http://localhost:3000/api/validate_user
# Content-Type: application/json

# {
#   "name": "John",
#   "email":  "kunasvcsl@example.com",
#   "password": "Cyber"
# }

# POST http://localhost:3000/api/add_user
# Content-Type: application/json

# {
#   "name": "John",
#   "email":  "kunasvcsl@example.com",
#   "password": "Cyber"
# }



# GET http://localhost:3000/api/users/
# Content-Type: application/json
